
# project_id = "okoaoguvtjauiecfajri"
[global]
project_id = "okoaoguvtjauiecfajri"

[env]
SUPABASE_URL = "env"
SUPABASE_SERVICE_ROLE_KEY = "env"
EVOLUTION_API_KEY = "env"
UPSTASH_REDIS_REST_URL = "env"
UPSTASH_REDIS_REST_TOKEN = "env"
ENABLE_MESSAGE_BUFFERING = "env"
