# Queue Processor Edge Function Configuration

[function]
# Function timeout in seconds (max 60 for Edge Functions)
timeout = 60

# Memory limit (not yet configurable in Supabase Edge Functions)
# memory = 512

[env]
# Environment variables needed for the function
# These should be set in Supabase dashboard or via CLI

# Redis Configuration (Required)
# UPSTASH_REDIS_REST_URL
# UPSTASH_REDIS_REST_TOKEN  

# Supabase Configuration (Required)
# SUPABASE_URL
# SUPABASE_SERVICE_ROLE_KEY

# Queue System Control (Optional)
# USE_QUEUE_SYSTEM=true (default) - Enable Redis queue system
# USE_QUEUE_SYSTEM=false - Emergency rollback to legacy buffering system