// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okoaoguvtjauiecfajri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rb2FvZ3V2dGphdWllY2ZhanJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1NDMzNTUsImV4cCI6MjA1NTExOTM1NX0.2r-gnK5O4SgSz8IKwAZGlg1IodKrdqQxa4xwVFn5z0o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Enhanced Supabase client with optimized auth configuration
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Automatically refresh the session when the access token expires
    // This prevents users from being logged out unexpectedly
    autoRefreshToken: true,

    // Persist the session in localStorage so users stay logged in
    // even after closing the browser
    persistSession: true,

    // Detect session from URL hash for OAuth callbacks (Google Sign-In, etc.)
    detectSessionInUrl: true,

    // Custom storage key for better organization
    storageKey: 'convgo-auth-token',

    // Use localStorage for session persistence
    storage: window.localStorage,

    // Use PKCE flow for enhanced security
    // PKCE (Proof Key for Code Exchange) is recommended for SPAs
    flowType: 'pkce',
  },
});