
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okoaoguvtjauiecfajri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rb2FvZ3V2dGphdWllY2ZhanJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1NDMzNTUsImV4cCI6MjA1NTExOTM1NX0.2r-gnK5O4SgSz8IKwAZGlg1IodKrdqQxa4xwVFn5z0o";

// Define global headers to ensure proper content negotiation
const globalHeaders = {
  'X-Client-Info': 'supabase-js/2.48.1',
  'Content-Type': 'application/json',
  'Accept': 'application/json',
  'Cache-Control': 'no-cache'
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true
    },
    global: {
      headers: globalHeaders
    }
  }
);
